language: php

php:
  - 5.4
  - 5.5

env:
  - CODECEPTION_VERSION="1.6.*"
  - CODECEPTION_VERSION="dev-master"

before_script:
  - composer require --no-update codeception/codeception:${CODECEPTION_VERSION}
  - composer install -n --prefer-dist --dev

script: "bin/codecept run"
